#Required: false or true only works on public repos. This repo is private.

name: 🐛 Bug Report
description: File a bug report
title: "Title"
labels: ["bug"]
projects: ["equinor/650"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Explain what happened in detail
      placeholder: Describe the issue here... and paste/drop in any screenshots too!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Clear, step-by-step insruction to replicate the bug
      placeholder: Provide a detailed sequence of actions to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: Expected results
      description: What was expected to happen
      placeholder: Describe the outcome that should have occured if the bug was not present
    validations:
      required: false
  - type: textarea
    id: results
    attributes:
      label: Actual results
      description: What actually occurred
      placeholder: Detail the incorrect or unexpected outcome observed due to the bug
    validations:
      required: true
  - type: textarea
    id: Information
    attributes:
      label: Other details
      description: Include any other relevant information 
      placeholder: For example logs, environment, code snippets, errorcodes etc
    validations:
      required: false
